spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/proyectoFlySky?useSSL=false&serverTimezone=UTC
    hikari:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations:
      - classpath:vuelos.sql
      - classpath:usuarios.sql
      - classpath:asientos.sql
      mode: always